### ISSUE TITLE
您好，能请教您代码中预处理部分的相关操作及原因是什么吗？

### ISSUE THREAD

**Issue by orangeKillery** [markub3327/HAR-Transformer#1]
您好，能请教您代码中预处理部分的相关操作及原因是什么吗？

**Comment by markub3327** [comment]
All are in the paper described. Thanks.

**Comment by orangeKillery** [comment]
Thank you for your reply. You're really nice. I'm a green hand. May I ask you how the broken samples in the code were obtained, and what is the reason for this part of the code？
indexes = []
for i in range(signals.shape[0]):
   for j in range(signals.shape[1]):
       if (np.abs(signals[i, j]) > 350.0):
           indexes.append(i)
           break
print(indexes)
print(f"Remove {len(indexes)} elements !")

why remove abs(signals[i, j]) > 350.0 , and then break?

**Comment by orangeKillery** [comment]
> All are in the paper described. Thanks.

I've read your paper several times, but I don't understand it

**Comment by AlmarhumTChalla** [comment]
They are bad samples, if you look at the data yourself you'll see that almost none of them are above 100 or under -100.

If you'd like to see a shorter code, here's mine:
```
df = pd.read_csv('../KU-HAR_time_domain_subsamples_20750x300.csv', header=None)
df = df.drop([6587, 6588, 6589, 6590, 6591, 6592, 6593, 6594, 6595, 6596, 6597, 6598, 6599, 6600, 6601, 6602, 6603, 6604, 6605, 6606, 6607, 6660, 6661, 6662, 6663, 6664, 6665, 6666, 6667, 6668, 6669, 6670, 6671, 6672, 6673, 6674, 6675, 6676, 6677, 6678, 6679, 6680, 6681, 6682, 6683, 6684, 6685, 6686, 6687, 6716, 6717, 6718, 6719, 6720, 6721, 6722, 6723, 6724, 6725, 6726, 6727, 6728, 6729, 6730, 6731, 6732, 6733, 6734, 6735, 6736, 6737, 6738, 6739, 6740, 6741, 6742, 6743, 6750, 6751, 6752, 6753, 6754, 6755, 6756, 6757, 6758, 6759, 6760, 6761, 6762, 6763, 6764, 6765, 6766, 6767])
X = np.stack([
    df.values[:, 0:300],
    df.values[:, 300:600],
    df.values[:, 600:900],
    df.values[:, 900:1200],
    df.values[:, 1200:1500],
    df.values[:, 1500:1800],
], axis=-1)
y = df.values[:, 1800]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)
```

**Comment by orangeKillery** [comment]
Thank you very much for your reply, it was very helpful.
