### ISSUE TITLE
  Ask about the version of the library

### ISSUE THREAD

**Issue by CoderSimilar** [markub3327/HAR-Transformer#5]
Hello! I am working hard to reproduce your code. What are the versions of the various frameworks and libraries you are using? For example, numpy, pandas, Scikit-learn, etc.

**Comment by markub3327** [comment]
Hello! I was using the latest versions of all libraries at that time. I guessed versions by date of commit:

TensorFlow 2.8.0
scikit-learn 1.0.2
Numpy version depends on version of TensorFlow !
Pandas 1.4.0
seaborn v0.12.2 (December 2022)
matplotlib v3.5.1

**Comment by CoderSimilar** [comment]
Thanks for your reply! This content will help me a lot, Thanks again!
